### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Ygarr** [gngrOrg/gngr#277]
Hello, build failed with these notifications
![2022-07-30_08-20](https://user-images.githubusercontent.com/14309871/181876020-19885164-89da-4c88-b362-b4c82966d676.png)
![2022-07-30_08-21](https://user-images.githubusercontent.com/14309871/181876021-493de7c4-a750-4887-b3c7-c836a946716f.png)

**Comment by hrj** [comment]
Hello @Ygarr 

1. The release date needs to be updated in [release.properties](https://github.com/gngrOrg/gngr/blob/master/src/Platform_Core/properties/release.properties) to shut off the warning message.

2. This is because Java 17 doesn't have support for Security Manager. You can enable it by adding a system property: `-Djava.security.manager=allow`

If this doesn't makes sense, please wait for a few more days. I will try to get the project up again.

**Comment by Ygarr** [comment]
changed release properties with  parameter kinda
"Version: 0.4-prealpha
Published on: 2022-07-18 "
and switch java from 18 to 17 without -Djava.security.manager=allow
and it builded somehow. Thanks

**Comment by Ygarr** [comment]
changed the  release.properties like 

version.string = 0.4-prealpha
version.number = 0
version.name = anonymous
version.releaseDate = 2022-07-18

and warning disappears.

**Comment by hrj** [comment]
Thanks for confirming. Closed via 37ec75777d8d115bac15b18aa73bda2e3d90a46b

Will make a new release soon.
